//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heroes5Calculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dwellings
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Faction { get; set; }
        public long Tier { get; set; }
        public long PopulationBonus { get; set; }
    }
}
