//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heroes5Calculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Units
    {
        public long ID { get; set; }
        public string NameBase { get; set; }
        public string NameUpg { get; set; }
        public string NameUpgToE { get; set; }
        public string Faction { get; set; }
        public Nullable<long> Tier { get; set; }
        public string ImageBase { get; set; }
        public string ImageUpg { get; set; }
        public string ImageUpgToE { get; set; }
        public long GoldCostBase { get; set; }
        public Nullable<long> GoldCostUpg { get; set; }
        public Nullable<long> PopulationBase { get; set; }
    }
}
